# Generated by Django 4.1.2 on 2022-10-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='recipe',
        ),
    ]
